/**
 * Game events and LLM-generated content types
 */

import { type EntityId, type Timestamp } from './common.js';

/** Event severity/importance */
export enum EventSeverity {
  Info = 'info',
  Warning = 'warning',
  Critical = 'critical',
  Opportunity = 'opportunity',
}

/** Event category */
export enum EventCategory {
  Market = 'market',
  Political = 'political',
  Technology = 'technology',
  Social = 'social',
  Environmental = 'environmental',
  Corporate = 'corporate',
  Personal = 'personal',
}

/** Game event - can be LLM generated */
export interface GameEvent {
  id: EntityId;
  
  // Content
  title: string;
  titleZh: string;
  headline: string;
  content: string;
  
  // Classification
  category: EventCategory;
  severity: EventSeverity;
  
  // Generation
  isLLMGenerated: boolean;
  generationContext?: EventGenerationContext;
  
  // Timing
  triggeredAt: Timestamp;
  duration?: number; // Ticks until effect ends
  
  // Effects
  effects: EventEffect[];
  
  // Player interaction
  requiresResponse: boolean;
  responseOptions?: EventResponseOption[];
  playerResponseId?: EntityId;
  
  // Visibility
  visibleToCompanies: EntityId[]; // Empty = public
  discoveredBy: EntityId[]; // Companies that have seen this
  
  // Chain events
  triggeredByEventId?: EntityId;
  triggersEventIds?: EntityId[];
}

export interface EventGenerationContext {
  trigger: 'scheduled' | 'condition' | 'player_action' | 'ai_action' | 'random';
  relevantEntities: EntityId[];
  marketConditions: Record<string, number>;
  prompt?: string;
}

export interface EventEffect {
  type: EventEffectType;
  targetType: 'goods' | 'company' | 'building' | 'pop_group' | 'technology' | 'global';
  targetId?: EntityId;
  
  // Effect parameters
  parameter: string;
  value: number;
  isMultiplier: boolean;
  
  // Duration
  permanent: boolean;
  durationTicks?: number;
  
  // Condition
  condition?: string; // LLM evaluatable condition
}

export enum EventEffectType {
  PriceModifier = 'price_modifier',
  DemandModifier = 'demand_modifier',
  SupplyModifier = 'supply_modifier',
  ReputationChange = 'reputation_change',
  TagInjection = 'tag_injection',
  TagRemoval = 'tag_removal',
  RegulationChange = 'regulation_change',
  TaxChange = 'tax_change',
  SubsidyGrant = 'subsidy_grant',
  FineImposed = 'fine_imposed',
  TechUnlock = 'tech_unlock',
  TechBlock = 'tech_block',
  ResourceDiscovery = 'resource_discovery',
  ResourceDepletion = 'resource_depletion',
}

export interface EventResponseOption {
  id: EntityId;
  label: string;
  description: string;
  cost?: number;
  requirements?: string[];
  effects: EventEffect[];
  llmFollowUp?: string; // Prompt for generating follow-up event
}

/** News article generated by LLM */
export interface NewsArticle {
  id: EntityId;
  eventId?: EntityId;
  
  headline: string;
  subheadline?: string;
  content: string;
  author: string; // Fake journalist name
  publication: string; // Fake news outlet
  
  // Bias and spin
  sentiment: 'positive' | 'negative' | 'neutral';
  targetCompanyId?: EntityId;
  sponsoredBy?: EntityId; // If player/AI paid for this
  
  publishedAt: Timestamp;
  
  // Impact tracking
  readByPopGroups: EntityId[];
  opinionImpact: Record<EntityId, number>; // Company ID -> opinion change
}

/** Market intelligence report */
export interface IntelligenceReport {
  id: EntityId;
  forCompanyId: EntityId;
  
  // Report content
  title: string;
  summary: string;
  detailedAnalysis: string;
  
  // What it's about
  subjectType: 'company' | 'market' | 'technology' | 'trend';
  subjectId?: EntityId;
  
  // Quality and reliability
  accuracy: number; // 0-1, how accurate this intel actually is
  confidence: number; // 0-1, how confident the report claims to be
  
  // Key insights (structured)
  insights: IntelligenceInsight[];
  
  // Recommendations
  recommendations: string[];
  
  generatedAt: Timestamp;
  expiresAt?: Timestamp;
}

export interface IntelligenceInsight {
  type: 'observation' | 'prediction' | 'warning' | 'opportunity';
  content: string;
  relatedEntityIds: EntityId[];
  confidence: number;
}

/** LLM conversation/negotiation message */
export interface LLMMessage {
  id: EntityId;
  conversationId: EntityId;
  
  role: 'system' | 'user' | 'assistant';
  content: string;
  
  // If from AI character
  characterId?: EntityId;
  characterName?: string;
  emotionalState?: string;
  
  // Metadata
  timestamp: Timestamp;
  tokenCount?: number;
}

/** Conversation with LLM (negotiation, research, etc.) */
export interface LLMConversation {
  id: EntityId;
  type: ConversationType;
  
  // Participants
  playerCompanyId: EntityId;
  aiCharacterId?: EntityId;
  
  // Context
  contextType: 'negotiation' | 'research' | 'espionage' | 'marketing' | 'legal';
  contextData: Record<string, unknown>;
  
  // Messages
  messages: LLMMessage[];
  
  // Outcome
  status: 'active' | 'completed' | 'abandoned';
  outcome?: ConversationOutcome;
  
  startedAt: Timestamp;
  lastMessageAt: Timestamp;
}

export enum ConversationType {
  ContractNegotiation = 'contract_negotiation',
  TalentRecruitment = 'talent_recruitment',
  ResearchConsultation = 'research_consultation',
  LegalDispute = 'legal_dispute',
  MediaInterview = 'media_interview',
  PoliticalLobbying = 'political_lobbying',
  EspionageDebrief = 'espionage_debrief',
}

export interface ConversationOutcome {
  success: boolean;
  resultType: string;
  resultData: Record<string, unknown>;
  summary: string;
}